# Copyright FUJITSU LIMITED 2015.

- name: /personium を作成
  file: state=directory path=/personium owner=root group=root mode=0755


- name: /opt/ap_piolog/dc-core を作成
  file: state=directory path=/opt/ap_piolog/dc-core owner=root group=root mode=0755

- name: /opt/ap_piolog/dc-core/log を作成
  file: state=directory path=/opt/ap_piolog/dc-core/log owner=personium group=personium mode=0755

- name: /personium/dc-core を作成
  file: state=directory path=/personium/dc-core owner=personium group=personium mode=0755

- name: /personium/dc-core に /opt/ap_piolog/dc-core/log の symlink を作成
  file: state=link src=/opt/ap_piolog/dc-core/log dest=/personium/dc-core/log owner=personium group=personium mode=0777

- name: /personium/dc-core/conf を作成
  file: state=directory path=/personium/dc-core/conf owner=root group=root mode=0755

- name: /personium/dc-core/conf/18888 を作成
  file: state=directory path=/personium/dc-core/conf/18888 owner=root group=root mode=0755

- name: /personium/dc-core/conf/28888 を作成
  file: state=directory path=/personium/dc-core/conf/28888 owner=root group=root mode=0755

- name: /personium/dc-core/conf/38888 を作成
  file: state=directory path=/personium/dc-core/conf/38888 owner=root group=root mode=0755

- name: /personium/dc-core/conf/48888 を作成
  file: state=directory path=/personium/dc-core/conf/48888 owner=root group=root mode=0755

- name: /opt/ap_piolog/dc-core/ads を作成
  file: state=directory path=/opt/ap_piolog/dc-core/ads owner=personium group=personium mode=0755

- name: /personium/dc-core に /opt/ap_piolog/dc-core/ads の symlink を作成
  file: state=link src=/opt/ap_piolog/dc-core/ads dest=/personium/dc-core/ads owner=personium group=personium mode=0777


- name: /opt/ap_piolog/dc-engine を作成
  file: state=directory path=/opt/ap_piolog/dc-engine owner=root group=root mode=0755

- name: /opt/ap_piolog/dc-engine/log を作成
  file: state=directory path=/opt/ap_piolog/dc-engine/log owner=personium group=personium mode=0755

- name: /personium/dc-engine を作成
  file: state=directory path=/personium/dc-engine owner=personium group=personium mode=0755

- name: /personium/dc-engine に /opt/ap_piolog/dc-engine/log の symlink を作成
  file: state=link src=/opt/ap_piolog/dc-engine/log dest=/personium/dc-engine/log owner=personium group=personium mode=0777

- name: /personium/dc-engine/extensions を作成
  file: state=directory path=/personium/dc-engine/extensions owner=personium group=personium mode=0755


- name: /opt/ap_piolog/personium を作成
  file: state=directory path=/opt/ap_piolog/personium owner=personium group=personium mode=0755

- name: /opt/ap_piolog/personium/log を作成
  file: state=directory path=/opt/ap_piolog/personium/log owner=personium group=personium mode=0755

- name: /personium/personium を作成
  file: state=directory path=/personium/personium owner=personium group=personium mode=0755

- name: /personium/personium に /opt/ap_piolog/personium/log の symlink を作成
  file: state=link src=/opt/ap_piolog/personium/log dest=/personium/personium/log owner=personium group=personium mode=0777


- name: /personium/18888 を作成
  file: state=directory path=/personium/18888 owner=personium group=personium mode=0755

- name: /personium/18888/dc-engine を作成
  file: state=directory path=/personium/18888/dc-engine owner=personium group=personium mode=0755

- name: /personium/18888/dc-engine/extensions を作成
  file: state=directory path=/personium/18888/dc-engine/extensions owner=personium group=personium mode=0755

- name: /personium/28888 を作成
  file: state=directory path=/personium/28888 owner=personium group=personium mode=0755

- name: /personium/28888/dc-engine を作成
  file: state=directory path=/personium/28888/dc-engine owner=personium group=personium mode=0755

- name: /personium/28888/dc-engine/extensions を作成
  file: state=directory path=/personium/28888/dc-engine/extensions owner=personium group=personium mode=0755

- name: /personium/38888 を作成
  file: state=directory path=/personium/38888 owner=personium group=personium mode=0755

- name: /personium/38888/dc-engine を作成
  file: state=directory path=/personium/38888/dc-engine owner=personium group=personium mode=0755

- name: /personium/38888/dc-engine/extensions を作成
  file: state=directory path=/personium/38888/dc-engine/extensions owner=personium group=personium mode=0755

- name: /personium/48888 を作成
  file: state=directory path=/personium/48888 owner=personium group=personium mode=0755

- name: /personium/48888/dc-engine を作成
  file: state=directory path=/personium/48888/dc-engine owner=personium group=personium mode=0755

- name: /personium/48888/dc-engine/extensions を作成
  file: state=directory path=/personium/48888/dc-engine/extensions owner=personium group=personium mode=0755


- name: /personium_nfs を作成
  file: state=directory path=/personium_nfs owner=root group=root mode=0755


- name: /opt/nfs1/dc-core を作成
  file: state=directory path=/opt/nfs1/dc-core owner=root group=root mode=0755

- name: /personium_nfs/dc-core を作成
  file: state=directory path=/personium_nfs/dc-core owner=personium group=personium mode=0755

- name: Creates directory
  file: path=/opt/nfs1/dc-core/dav state=directory owner=personium group=personium mode=0777

- name: /personium_nfs/dc-core に /opt/nfs1/dc-core/dav の symlink を作成
  file: state=link src=/opt/nfs1/dc-core/dav dest=/personium_nfs/dc-core/dav owner=personium group=personium mode=0777

- name: Creates directory
  file: path=/opt/nfs1/dc-core/eventlog state=directory owner=personium group=personium mode=0777

- name: /personium_nfs/dc-core に /opt/nfs1/dc-core/eventlog の symlink を作成
  file: state=link src=/opt/nfs1/dc-core/eventlog dest=/personium_nfs/dc-core/eventlog owner=personium group=personium mode=0777

- name: Creates directory
  file: path=/opt/nfs1/dc-core/barInstall state=directory owner=personium group=personium mode=0777

- name: /personium_nfs/dc-core に /opt/nfs1/dc-core/dav の symlink を作成
  file: state=link src=/opt/nfs1/dc-core/barInstall dest=/personium_nfs/dc-core/barInstall owner=personium group=personium mode=0777
