# Copyright FUJITSU LIMITED 2015.

- name: /personium を作成
  file: state=directory path=/personium owner=root group=root mode=0755


#- name: /opt/nfs_piolog/dc-core を作成
#  file: state=directory path=/opt/nfs_piolog/dc-core owner=root group=root mode=0755

#- name: /opt/nfs_piolog/dc-core/log を作成
#  file: state=directory path=/opt/nfs_piolog/dc-core/log owner=personium group=personium mode=0755

#- name: /personium/dc-core を作成
#  file: state=directory path=/personium/dc-core owner=personium group=personium mode=0755

#- name: /personium/dc-core に /opt/nfs_piolog/dc-core/log の symlink を作成
#  file: state=link src=/opt/nfs_piolog/dc-core/log dest=/personium/dc-core/log owner=personium group=personium mode=0777

#- name: /opt/nfs_piolog/dc-engine を作成
#  file: state=directory path=/opt/nfs_piolog/dc-engine owner=root group=root mode=0755

#- name: /opt/nfs_piolog/dc-engine/log を作成
#  file: state=directory path=/opt/nfs_piolog/dc-engine/log owner=personium group=personium mode=0755

#- name: /personium/dc-engine を作成
#  file: state=directory path=/personium/dc-engine owner=personium group=personium mode=0755

#- name: /personium/dc-engine に /opt/nfs_piolog/dc-engine/log の symlink を作成
#  file: state=link src=/opt/nfs_piolog/dc-engine/log dest=/personium/dc-engine/log owner=personium group=personium mode=0777


#- name: /opt/nfs_piolog/logback を作成
#  file: state=directory path=/opt/nfs_piolog/logback owner=root group=root mode=0755

#- name: /opt/nfs_piolog/logback/log を作成
#  file: state=directory path=/opt/nfs_piolog/logback/log owner=personium group=personium mode=0755

- name: /personium/logback を作成
  file: state=directory path=/personium/logback owner=personium group=personium mode=0755

- name: /personium/logback/log を作成
  file: state=directory path=/personium/logback/log owner=personium group=personium mode=0755

#- name: /personium/logback に /opt/nfs_piolog/logback/log の symlink を作成
#  file: state=link src=/opt/nfs_piolog/logback/log dest=/personium/logback/log owner=personium group=personium mode=0777


- name: /personium_nfs を作成
  file: state=directory path=/personium_nfs owner=root group=root mode=0755


- name: /opt/nfs_webdav/dc-core を作成
  file: state=directory path=/opt/nfs_webdav/dc-core owner=root group=root mode=0755

- name: /opt/nfs_webdav/dc-core/dav を作成
  file: state=directory path=/opt/nfs_webdav/dc-core/dav owner=personium group=personium mode=0755

- name: /opt/nfs_webdav/dc-core/eventlog を作成
  file: state=directory path=/opt/nfs_webdav/dc-core/eventlog owner=personium group=personium mode=0755

- name: /opt/nfs_webdav/dc-core/barInstall を作成
  file: state=directory path=/opt/nfs_webdav/dc-core/barInstall owner=personium group=personium mode=0755

- name: /personium_nfs/dc-core を作成
  file: state=directory path=/personium_nfs/dc-core owner=personium group=personium mode=0755

- name: /personium_nfs/dc-core に /opt/nfs_webdav/dc-core/dav の symlink を作成
  file: state=link src=/opt/nfs_webdav/dc-core/dav dest=/personium_nfs/dc-core/dav owner=personium group=personium mode=0777

- name: /personium_nfs/dc-core に /opt/nfs_webdav/dc-core/eventlog の symlink を作成
  file: state=link src=/opt/nfs_webdav/dc-core/eventlog dest=/personium_nfs/dc-core/eventlog owner=personium group=personium mode=0777

- name: /personium_nfs/dc-core に /opt/nfs_webdav/dc-core/barInstall の symlink を作成
  file: state=link src=/opt/nfs_webdav/dc-core/barInstall dest=/personium_nfs/dc-core/barInstall owner=personium group=personium mode=0777
