# Copyright FUJITSU LIMITED 2015.

- name: ログ用ディレクトリを作成
  file: "state=directory path=/opt/es_data-log/elasticsearch-{{ version }}/log owner=elasticsearch group=elasticsearch recurse=yes"

#- name: ログ用ディレクトリを作成
#  file: "state=directory path=/opt/es_log/elasticsearch-{{ version }}/log owner=elasticsearch group=elasticsearch recurse=yes"

- name: データ用ディレクトリを作成
  file: "state=directory path=/opt/es_data-log/elasticsearch-{{ version }}/data owner=elasticsearch group=elasticsearch recurse=yes"

- name: ワーク用ディレクトリを作成
  file: "state=directory path=/opt/es_data-log/elasticsearch-{{ version }}/work owner=elasticsearch group=elasticsearch recurse=yes"

#- name: /fj のディレクトリを作成
#  file: "state=directory path=/fj owner=root group=root"

- name: /fj/elasticsearch-{{ version }}のディレクトリを作成
  file: "state=directory path=/fj/elasticsearch-{{ version }} owner=elasticsearch group=elasticsearch recurse=yes"

- name: log ディレクトリのシンボリックリンクを作成
  file: "state=link src=/opt/es_data-log/elasticsearch-{{ version }}/log dest=/fj/elasticsearch-{{ version }}/log owner=elasticsearch group=elasticsearch"

#- name: log ディレクトリのシンボリックリンクを作成
#  file: "state=link src=/opt/es_log/elasticsearch-{{ version }}/log dest=/fj/elasticsearch-{{ version }}/log owner=elasticsearch group=elasticsearch"

- name: data ディレクトリのシンボリックリンクを作成
  file: "state=link src=/opt/es_data-log/elasticsearch-{{ version }}/data dest=/fj/elasticsearch-{{ version }}/data owner=elasticsearch group=elasticsearch"

- name: work ディレクトリ のシンボリックリンクを作成
  file: "state=link src=/opt/es_data-log/elasticsearch-{{ version }}/work dest=/fj/elasticsearch-{{ version }}/work owner=elasticsearch group=elasticsearch"

- name: /fj/elasticsearch のシンボリックリンクを作成
  file: "state=link src=/fj/elasticsearch-{{ version }} dest=/fj/elasticsearch owner=elasticsearch group=elasticsearch"


