# Copyright FUJITSU LIMITED 2015.

- name: group の作成
  group: name=nginx gid=2010 state=present

- name: user の作成
  user: name=nginx uid=2010 shell=/sbin/nologin group=nginx home=/personium/nginx/lib comment="Nginx Administrator" createhome=no

- name: /personium のディレクトリを作成
  file: "state=directory path=/personium owner=root group=root"

- name: /personium/nginx を作成
  file: state=directory path=/personium/nginx owner=root group=root mode=0755

- name: /personium/nginx/lib を作成
  file: state=directory path=/personium/nginx/lib owner=nginx group=root mode=0755

- name: /personium/nginx/log を作成
  file: state=directory path=/personium/nginx/log owner=root group=root mode=0755

- name: /personium/nginx/log/main を作成
  file: state=directory path=/personium/nginx/log/main owner=root group=root mode=0755

- name: /personium/nginx/log/accesslog_443 を作成
  file: state=directory path=/personium/nginx/log/accesslog_443 owner=root group=root mode=0755

- name: /personium/nginx/log/accesslog_80 を作成
  file: state=directory path=/personium/nginx/log/accesslog_80 owner=root group=root mode=0755


- name: /personium/var を作成 (互換用)
  file: state=directory path=/personium/var owner=root group=root mode=0755

- name: /personium/var/lib を作成 (互換用)
  file: state=directory path=/personium/var/lib owner=root group=root mode=0755

- name: /personium/var/log を作成 (互換用)
  file: state=directory path=/personium/var/log owner=root group=root mode=0755


- name: /opt/var を作成 (互換用)
  file: state=directory path=/opt/var owner=root group=root mode=0755

- name: /opt/var/lib を作成 (互換用)
  file: state=directory path=/opt/var/lib owner=root group=root mode=0755

- name: /opt/var/log を作成 (互換用)
  file: state=directory path=/opt/var/log owner=root group=root mode=0755

- name: /opt/var/lib/nginx を /personium/nginx/lib への symlink として作成 (互換用)
  file: state=link src=/personium/nginx/lib dest=/opt/var/lib/nginx owner=root group=root mode=0777

- name: /opt/var/log/nginx を /personium/nginx/log への symlink として作成 (互換用)
  file: state=link src=/personium/nginx/log dest=/opt/var/log/nginx owner=root group=root mode=0777
